name: gymsync
description: "Show your gym workouts at Discord RPC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  flutter_svg: ^2.0.10
  confetti: ^0.7.0
  health: ^13.1.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  flutter_background: ^1.0.1
  workmanager: ^0.5.2
  flutter_foreground_task: ^8.11.0
  restart_app: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.0.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0
  permission_handler: ^11.0.1
  dynamic_app_icon: ^0.0.1+1
  url_launcher: ^6.2.6
  webview_flutter: ^4.0.7
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/infinity_blue.png
    - assets/infinity_red.png
    - assets/infinity_green.png