name: Build Desktop Presence MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_desktop_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          architecture: x64

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify environments
        run: |
          flutter --version
          dart --version
          node --version
          npm --version

      - name: Build Desktop Presence
        run: |
          cd apps/presence
          npm install
          npm run build

      - name: Zip Desktop Presence MacOS build
        run: |
          cd apps/presence/dist
          zip -r desktop-presence-macos.zip macos-unpacked

      - name: Upload Desktop Presence artifact MacOS
        uses: actions/upload-artifact@v4
        with:
          name: desktop-presence-macos
          path: apps/presence/dist/desktop-presence-macos.zip
