name: Build Desktop Presence Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_desktop_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Flutter
        run: |
          sudo apt update && sudo apt install -y curl git unzip xz-utils zip libglu1-mesa libc6:amd64 libstdc++6:amd64 lib32z1 libbz2-1.0:amd64

      - name: Download and setup Flutter
        run: |
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.32.6-stable.tar.xz
          tar xf flutter_linux_3.32.6-stable.tar.xz
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Verify environments
        run: |
          flutter --version
          dart --version
          node --version
          npm --version

      - name: Build Desktop Presence
        run: |
          cd apps/presence
          npm install
          npm run build

      - name: Zip Desktop Presence Linux build
        run: |
          cd apps/presence/dist
          zip -r desktop-presence-linux.zip linux-unpacked

      - name: Upload Desktop Presence artifact Linux
        uses: actions/upload-artifact@v4
        with:
          name: desktop-presence-linux
          path: apps/presence/dist/desktop-presence-linux.zip
