name: Build APK with Makefile, Upload to BrowserStack and Run Espresso Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk make curl jq

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APKs using Makefile
        run: |
          make

      - name: Upload app APK to BrowserStack
        id: upload_app
        run: |
          RESPONSE=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST https://api-cloud.browserstack.com/app-automate/upload \
            -F "file=@./app/build/outputs/apk/debug/app-debug.apk")
          echo "RESPONSE: $RESPONSE"
          echo "APP_URL=$(echo "$RESPONSE" | jq -r '.app_url')" >> "$GITHUB_ENV"

      - name: Upload test APK to BrowserStack
        id: upload_test
        run: |
          RESPONSE=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST https://api-cloud.browserstack.com/app-automate/espresso/test-suite \
            -F "file=@./tests/app-debug-androidTest.apk")
          echo "RESPONSE: $RESPONSE"
          echo "TEST_URL=$(echo "$RESPONSE" | jq -r '.test_url')" >> "$GITHUB_ENV"

      - name: Run Espresso test on BrowserStack
        id: run_test
        run: |
          echo "Running Espresso test on BrowserStack..."
          echo "APP_URL=$APP_URL"
          echo "TEST_URL=$TEST_URL"
          RESPONSE=$(curl -s -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST https://api-cloud.browserstack.com/app-automate/espresso/build \
            -d "{\"app\":\"$APP_URL\",\"testSuite\":\"$TEST_URL\"}" \
            -H "Content-Type: application/json")
          echo "RUN_RESPONSE: $RESPONSE"

          echo "$RESPONSE" | jq .
          BUILD_ID=$(echo "$RESPONSE" | jq -r '.build_id')
          
          if [ "$BUILD_ID" = "null" ] || [ -z "$BUILD_ID" ]; then
            echo "Failed to extract build_id"
            exit 1
          fi
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV

      - name: Show BrowserStack Dashboard Link
        run: |
          echo "✅ Tests running on BrowserStack:"
          echo "https://app-automate.browserstack.com/builds/$BUILD_ID"
