name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'apps/mobile_app/**'
      - 'apps/presence/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'apps/mobile_app/**'
      - 'apps/presence/**'
  workflow_dispatch:

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: apps/backend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  mobile_app:
    name: Mobile App Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mobile_app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  presence:
    name: Presence App Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/presence
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: apps/presence/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
